### ISSUE TITLE
Compilation issues on Debian (Jessie)

### ISSUE THREAD

**Issue by b-zijlstra** [imc-codeteam/veevee#3]
When running 'make' out-of-the-box I get the following error: ['round' is not a member of 'std'](http://stackoverflow.com/questions/12696764/round-is-not-a-member-of-std)
- Fix: Add compilation tag ```-std=c++0x```

After the above fix I get the following error: [undefined reference to symbol 'pcre_study'](http://stackoverflow.com/questions/6509834/how-can-i-link-my-c-code-with-the-pcre-library-linker-errors-currently-being-t)
- Fix: Like with Darwin, end the LDFLAGS with ```-lpcre```

With the above two fixes the compilation succeeds, with a few ```-Wsign-compare``` warnings.

**Comment by ifilot** [comment]
Fixed!
