### ISSUE TITLE
Program execution is limited to the root directory.

### ISSUE THREAD

**Issue by b-zijlstra** [imc-codeteam/veevee#4]
The program is executed correctly from the root directory, e.g. ```veevee$ bin/veevee examples/OUTCAR```.
However, execution from other directories, e.g. ```veevee/bin$ ./veevee ../examples/OUTCAR```, gives the following output:
```
Could not load font!
Could not load font!
Could not load font!
Segmentation fault
```

Probably the font paths are relative to the directory of execution, rather than to the executable or project root.

**Comment by ifilot** [comment]
Correct. I would either like to embed the fonts into the C++ program, use system fonts or link to them relatively. I haven't found the best solution to this problem yet.

**Comment by ifilot** [comment]
I have decided to embed the fonts directly into the program by means of a static unsigned char array in a header file. The program no longer depends on external font files.
