### ISSUE TITLE
improper transposed unit cell matrix

### ISSUE THREAD

**Issue by rjpbroos** [imc-codeteam/veevee#6]
When using veevee on an OUTCAR for a Rh60Fe24 unit cell (which is 11-1) and just saving it as a POSCAR results in a discrepancy in the output, yielding an improper unit cell. 

The OUTCAR can be found at https://www.dropbox.com/s/7bio8wf6byyytzs/OUTCAR?dl=0

**Comment by ifilot** [comment]
This problem only arises for non-prismatic unit cells. It relates to the calculation of the unitcell matrix inverse. This inverse matrix had to be transposed, which was not the case.

The problem is solved as of version 1.1.5.0.
