### ISSUE TITLE
Bug in POSCAR creation

### ISSUE THREAD

**Issue by rjpbroos** [imc-codeteam/veevee#7]
When adding multiple polyatomic molecules, e.g. 2 CO molecules on the surface, the POSCAR which can be saved is wrong. In this case, the first CO will consist of 2 C atoms, where the second CO consists of 2 O atoms. Something goes wrong with the sorting of the POSCAR with the added species.

**Comment by ifilot** [comment]
When adding fragments, the new atoms were appended to the atoms array without sorting them by element (required for VASP POSCARS). This is now resolved.
